[[redirects]]
  from = "/contactform"
  to = "https://hooks.zapier.com/hooks/catch/8656224/ogh0to4/"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[build.environment]
    NPM_FLAGS="--prefix=/dev/null"